version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: rakshasetu-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: rakshasetu
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
